[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "multipart"] }
tokio = { version = "1", features = ["full"] }
types = { path = "../types" }
aes-gcm-siv = "0.10.3"
rand = "0.8.4"
rust-argon2 = "0.8"

serde_json = { version = "1.0", default-features = false, features = ["alloc"] }